# Define sensitive variables in write protected files (chmod 600) and use then as secrets
# Makes it possible to share/git the docker-compose.yml file without sharing sensitive data
# Make sure the secrets folder is added to the .gitignore file
secrets:
  duckdns_token:
    file: ${DOCKER_CONFIG_DIR}/secrets/duckdns_token.secrets

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228
  
# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID
  
x-security: &common-key-security
  security_opt:
    - no-new-privileges

# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  <<: *common-key-security
  restart: always
  profiles:
  - core

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  <<: *common-key-security
  restart: unless-stopped
  networks:
    proxy:
  environment:
    <<: *default-tz-puid-pgid
  profiles:
  - apps

# Keys common to some of the services in media-services.txt
x-common-keys-media: &common-keys-media
  <<: *common-key-security
  restart: "no"
  networks:
    proxy:
  environment:
    <<: *default-tz-puid-pgid
  profiles:
  - media

networks:
  default:
  proxy:
    name: proxy
  socket_proxy:
    name: socket_proxy

volumes:
  letsencrypt_certificates:
    name: letsencrypt_certificates
  nfs_books:
    driver: local
    name: books    # this is the name of the volume in /var/lib/docker/volumes
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NAS_IP},rw
      device: ":${BOOKS_DIR}"

# include:
#   - ./compose/docker-socket-proxy.yml
#   - ./compose/traefik.yml

services:
  ############### CORE Services
  traefik:
    extends:
      service: traefik
      file: ./compose/traefik.yml
    <<: *common-keys-core

  docker-socket-proxy:
    extends:
      service: docker-socket-proxy
      file: ./compose/docker-socket-proxy.yml
    <<: *common-keys-core

  ############### APPS Services
  whoami:
    extends:
      service: whoami
      file: ./compose/whoami.yml
    <<: *common-keys-apps

  calibre:
    extends:
      service: calibre
      file: ./compose/calibre.yml
    <<: *common-keys-apps

  calibre-web:
    extends:
      service: calibre-web
      file: ./compose/calibre.yml
    <<: *common-keys-apps

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: ${PROJECT_NAME}-prowlarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/prowlarr:/config:rw
      # - ${DOCKERNASSTORAGEDIR}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.entrypoints: websecure
    networks:
      proxy:

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: ${PROJECT_NAME}-readarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/readarr:/config:rw
      - nfs_books:/data/media/books:rw
    labels:
      traefik.enable: true
      traefik.http.routers.readarr.entrypoints: websecure
    networks:
      proxy:
    depends_on:
      - prowlarr
