services:
  calibre:
    image: lscr.io/linuxserver/calibre:${CALIBRE_VERSION}
    container_name: ${PROJECT_NAME}-calibre
    volumes:
      - ${DOCKER_CONFIG_DIR}/calibre/config:/config:rw
      - nfs_books:/data/media/books:rw
    labels:
      traefik.enable: true
      traefik.http.routers.calibre.entrypoints: websecure
      traefik.http.services.calibre.loadbalancer.server.port: 8080

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:${CALIBRE_WEB_VERSION}
    container_name: ${PROJECT_NAME}-calibre-web
    environment:
      DOCKER_MODS: linuxserver/mods:universal-calibre
    volumes:
      - ${DOCKER_CONFIG_DIR}/calibre/calibre-web:/config:rw
      - nfs_books:/data/media/books:rw
    labels:
      traefik.enable: true
      traefik.http.routers.calibre-web.entrypoints: websecure
      traefik.http.routers.calibre-web.rule: Host(`books.${DOMAIN_NAME}`)
      traefik.http.services.calibre-web.loadbalancer.server.port: 8083
      # Creates a middleware that adds in a header to tell Calibre-Web the X-Scheme is https
      # (this is similar to the nginx examples) and required for Kobo Sync
      traefik.http.middlewares.kobo-sync-headers.headers.customrequestheaders.X-Scheme: https
      # traefik.http.routers.calibre-web.middlewares: secure-headers,kobo-sync-headers
      traefik.http.routers.calibre-web.middlewares: kobo-sync-headers