services:
  pihole:
    image: pluim003/pihole-unbound
    container_name: ${PROJECT_NAME}-pihole
    # ports:
    #   # https://community.traefik.io/t/pihole-tcp-udp-services-for-port-53-behind-traefik/6719/7
    #   - ${NS1}:53:53 # Allow localhost to be used as a dns resolver
    #   - ${NS1}:53:53/udp # Allow localhost to be used as a dns resolver
    networks:
      proxy:
    secrets:
      - pihole_password
    environment:
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSMASQ_LISTENING: all
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: local
      REV_SERVER_TARGET: ${GATEWAY_IP}
      REV_SERVER_CIDR: ${PIHOLE_CIDR}
      FTLCONF_LOCAL_IPV4: ${NS1}
      FTLCONF_RATE_LIMIT: 10000/60
      DNSSEC: "true"
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      WEBTHEME: default-dark
    volumes:
      - ${DOCKER_CONFIG_DIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ${DOCKER_CONFIG_DIR}/pihole/pihole:/etc/pihole
      - ${DOCKER_CONFIG_DIR}/pihole/unbound_pi-hole.conf:/etc/unbound/unbound.conf.d/pi-hole.conf
    labels:
      traefik.enable: true
      traefik.http.routers.pihole-rtr.entrypoints: websecure
      traefik.http.services.pihole-svc.loadbalancer.server.port: 80
      traefik.tcp.routers.dns-tcp-rtr.rule: HostSNI(`*`)
      traefik.tcp.routers.dns-tcp-rtr.entrypoints: dns-tcp
      traefik.tcp.routers.dns-tcp-rtr.service: dns-tcp-svc
      traefik.tcp.services.dns-tcp-svc.loadbalancer.server.port: 53
      traefik.udp.routers.dns-udp-rtr.entrypoints: dns-udp
      traefik.udp.routers.dns-udp-rtr.service: dns-udp-svc
      traefik.udp.services.dns-udp-svc.loadbalancer.server.port: 53

      # traefik.tcp.routers.pihole-dns-rtr.entrypoints: dns
      # traefik.tcp.routers.pihole-dns-rtr.rule: HostSNI(`$`)
      # traefik.tcp.routers.pihole-dns-rtr.tls: true
      # traefik.tcp.routers.pihole-dns-rtr.service: pihole-dns-svc
      # traefik.tcp.services.pihole-dns-svc.loadbalancer.server.port: 53
