services:
  orbital-sync:
    image: ghcr.io/mattwebbio/orbital-sync:${ORBITAL_SYNC_VERSION}
    container_name: ${PROJECT_NAME}-orbital-sync
    secrets:
      - pihole_password
    environment:
      PRIMARY_HOST_BASE_URL: https://pihole.${DOMAIN_NAME}
      PRIMARY_HOST_PASSWORD_FILE: /run/secrets/pihole_password
      SECONDARY_HOSTS_1_BASE_URL: https://pihole-xcp.${DOMAIN_NAME}
      SECONDARY_HOSTS_1_PASSWORD_FILE: /run/secrets/pihole_password